// Generated by gemini

import eslint from '@eslint/js';
// import css from '@eslint/css';
import html from '@html-eslint/eslint-plugin';
import parserHtml from '@html-eslint/parser';
import globals from 'globals';


export default [
  {
    // Global ignores
    ignores: ['node_modules/', 'dist/'],
  },
  
  // Base JavaScript configuration
  eslint.configs.recommended,
  // JS file configuration
  {
    files: ['**/*.js'],
    languageOptions: {
      globals: globals.browser,
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      // You can add or override JavaScript rules here
      // Example: 'no-console': 'warn',
    },
  },

  // HTML file configuration
  {
    files: ['**/*.html'],
    plugins: {
      html,
    },
    languageOptions: {
      // This tells ESLint to use the HTML parser for .html files
      parser: parserHtml,
    },
    rules: {
      // Use the recommended ruleset from the HTML plugin
      ...html.configs.recommended.rules,
      
      // You can add or override HTML rules here
      // Example: 'html/no-duplicate-id': 'error',
    },
  },

  // // CSS file configuration
  // {
  //   files: ['**/*.css'],
  //    languageOptions: {
  //     parser: css.parser, // tells ESLint to use the CSS parser
  //   },
  //   plugins: {
  //     css,
  //   },
  //   rules: {
  //     // Use the recommended ruleset from the CSS plugin
  //     ...css.configs.recommended.rules,

  //     // You can add other CSS rules here
  //     // Example: 'css/no-empty-blocks': 'error',
  //   },
  // },
];